apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
type: Opaque
stringData:
  JWT_SECRET: "banking_devops_super_secret_change_in_production"
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "secure_password_change_in_production"
  MONGO_URI: "mongodb://admin:secure_password_change_in_production@mongodb-service:27017/banking_db?authSource=admin"
# NOTE: In production, use sealed-secrets or AWS Secrets Manager instead of plain stringData
